version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "410772457866"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building Telemetry API...
      - docker build -f Dockerfile.producer -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-telemetry-api:latest .
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-telemetry-api:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-telemetry-api:$IMAGE_TAG
      
      - echo Building Event Processor...
      - docker build -f Dockerfile.consumer -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-processor:latest .
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-processor:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-processor:$IMAGE_TAG
      
      - echo Building Analytics API...
      - docker build -f Dockerfile.graphql -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-analytics-api:latest .
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-analytics-api:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-analytics-api:$IMAGE_TAG
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-telemetry-api:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-telemetry-api:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-processor:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-processor:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-analytics-api:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/event-platform-analytics-api:$IMAGE_TAG
      
      - echo Updating ECS services...
      - aws ecs update-service --cluster event-platform-cluster --service event-platform-telemetry-api --force-new-deployment --region $AWS_DEFAULT_REGION
      - aws ecs update-service --cluster event-platform-cluster --service event-platform-processor --force-new-deployment --region $AWS_DEFAULT_REGION
      - aws ecs update-service --cluster event-platform-cluster --service event-platform-analytics-api --force-new-deployment --region $AWS_DEFAULT_REGION
      - aws ecs update-service --cluster event-platform-cluster --service event-platform-prometheus --force-new-deployment --region $AWS_DEFAULT_REGION
      - aws ecs update-service --cluster event-platform-cluster --service event-platform-prometheus --force-new-deployment --region $AWS_DEFAULT_REGION
      
      - echo Deployment initiated successfully!

artifacts:
  files:
    - '**/*'
