FROM prom/prometheus:v2.51.2

# Copy Prometheus config
COPY infra/monitoring/prometheus-ecs.yml /etc/prometheus/prometheus.yml

# Start Prometheus
CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus"]
